import { describe, expect, it } from "vitest";
import { SessionStateMachine, HandoffEngine, type StateCheckpoint, ContextRecoveryEngine } from "./session-engine.js";

describe("Wave 2: State Machine Transitions", () => {
  it("rejects invalid phase transitions", () => {
    const sm = new SessionStateMachine();
    // Valid initial transition
    expect(() => sm.transition("planning")).not.toThrow();

    // Valid sequential transition
    expect(() => sm.transition("execution")).not.toThrow();
    expect(() => sm.transition("verification")).not.toThrow();
    expect(() => sm.transition("completed")).not.toThrow();

    // Invalid transition backwards
    expect(() => sm.transition("execution")).toThrow("invalid_transition");
  });

  it("requires valid initial state", () => {
    const sm = new SessionStateMachine();
    // Invalid initial states
    expect(() => sm.transition("execution")).toThrow("invalid_transition");
    expect(() => sm.transition("completed")).toThrow("invalid_transition");
  });
});

describe("Wave 3: Checkpoint Persistence", () => {
  it("creates and loads versioned checkpoints", () => {
    const sm = new SessionStateMachine();
    sm.transition("planning");

    // Simulate updating some state
    const originalState: StateCheckpoint = {
      objective: "Build a feature",
      current_phase: sm.currentPhase,
      completed_work: ["setup"],
      current_work: "write tests",
      remaining_work: ["implement", "submit"],
      decisions: ["use vitest"],
      assumptions: [],
      tests_passed: [],
      tests_failed: ["initial_test"],
      blockers: [],
      branches: ["feature-branch"],
      commits: [],
      prs: [],
      evidence: [],
      next_action: "implement fix",
      checkpoint_version: 0 // starting version
    };

    const engine = new HandoffEngine();

    const serialized = engine.createCheckpoint(originalState);
    expect(serialized).toBeDefined();

    const loadedState = engine.loadCheckpoint(serialized);

    // Verify it bumped the version inside createCheckpoint
    expect(loadedState).toEqual({ ...originalState, checkpoint_version: 1 });
    expect(loadedState.checkpoint_version).toBe(1);

    // Version increment validation
    const nextCheckpoint = engine.createCheckpoint({...loadedState});
    const loadedNext = engine.loadCheckpoint(nextCheckpoint);
    expect(loadedNext.checkpoint_version).toBe(2);
  });
});

describe("Wave 4: Context Recovery Engine", () => {
  it("rebuilds state from durable truth + Git + evidence after a lost session", () => {
    // Durable truth from DB
    const durableTruth: StateCheckpoint = {
      objective: "Fix bug 123",
      current_phase: "execution",
      completed_work: ["Identify root cause"],
      current_work: "Implementing the fix",
      remaining_work: ["Testing", "Deployment"],
      decisions: ["Use specific API endpoint"],
      assumptions: ["API will respond within 500ms"],
      tests_passed: [],
      tests_failed: [],
      blockers: [],
      branches: [],
      commits: [],
      prs: [],
      evidence: [],
      next_action: "write failing test",
      checkpoint_version: 5
    };

    // Git state (e.g. from local branch query)
    const gitState = {
      branches: ["fix-bug-123"],
      commits: ["a1b2c3d"]
    };

    // Evidence generated by previous execution (e.g. from MCG or filesystem)
    const evidenceState = {
      tests_passed: ["test_api_connection"],
      evidence: ["API logs confirming root cause"]
    };

    const recoveryEngine = new ContextRecoveryEngine();

    const rebuiltState = recoveryEngine.rebuildTaskState(durableTruth, gitState, evidenceState);

    // Core details must match original durable truth
    expect(rebuiltState.objective).toBe("Fix bug 123");
    expect(rebuiltState.decisions).toEqual(["Use specific API endpoint"]);
    expect(rebuiltState.next_action).toBe("write failing test");

    // Branches and commits must incorporate Git truth
    expect(rebuiltState.branches).toEqual(["fix-bug-123"]);
    expect(rebuiltState.commits).toEqual(["a1b2c3d"]);

    // Evidence state must reflect passed tests and collected evidence
    expect(rebuiltState.tests_passed).toEqual(["test_api_connection"]);
    expect(rebuiltState.evidence).toEqual(["API logs confirming root cause"]);

    // Recovery engine should have advanced the checkpoint version to indicate a recovery commit
    expect(rebuiltState.checkpoint_version).toBe(6);
  });
});
