const views = [
  ['Overview', 'Visão geral'], ['History', 'Histórico'], ['Traces', 'Traces'],
  ['Tasks', 'Tarefas'], ['Agents', 'Agentes'], ['Tools', 'Ferramentas'],
  ['Plugins', 'Plugins / Skills'], ['MCPs', 'MCPs'], ['Graph', 'Contexto / Graph'], ['Executions', 'Execuções'],
  ['Cache', 'Cache'], ['Memory', 'Memória'], ['Validation', 'Validação MCG'], ['Alerts', 'Alertas']
];

const navGlyphs = { Overview: '▦', History: '◷', Traces: '⌁', Tasks: '✓', Agents: '◎', Tools: '⌘', Plugins: '⊞', MCPs: '⇄', Graph: '⌘', Executions: '▤', Cache: '◒', Memory: '≋', Validation: '✓', Alerts: '!' };
const navigation = views.map(([key, label]) => `<button class="nav-item" type="button" data-view="${key}" aria-current="${key === 'Overview' ? 'page' : 'false'}"><span class="nav-mark" aria-hidden="true">${navGlyphs[key]}</span><span>${label}</span></button>`).join('');

export const dashboardHtml = `<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="rgb(0, 0, 0)"><title>Lumenva Context Gateway</title>
<style>
:root{color-scheme:dark;--bg:rgb(0, 0, 0);--sidebar:rgb(16, 16, 17);--surface-primary:rgb(20, 20, 20);--surface:rgb(25, 25, 25);--card:rgb(25, 25, 25);--surface-2:rgb(31, 31, 31);--surface-3:rgb(43, 43, 43);--line:rgb(48, 48, 48);--gray-mid:rgb(64, 64, 64);--gray-secondary:rgb(119, 119, 119);--text:rgb(245, 245, 245);--sub:rgb(153, 153, 153);--muted:rgb(153, 153, 153);--blue:#79aaff;--cyan:rgb(0, 230, 118);--green:rgb(0, 230, 118);--green-glow:rgb(0, 255, 106);--red:rgb(239, 68, 68);--red-strong:rgb(255, 18, 48);--glass:rgba(25, 25, 25, 0.72);--glass-border:rgba(255, 255, 255, 0.10);--highlight:rgba(255, 255, 255, 0.06);--shadow:rgba(0, 0, 0, 0.45);--green-glow-shadow:rgba(0, 255, 106, 0.30);--red-glow-shadow:rgba(255, 18, 48, 0.30);--purple:#b39dff;--orange:#ffbf69;--focus:#79aaff}
:root[data-theme="light"] .nav-item:hover,:root[data-theme="light"] .action:hover{background:var(--surface-3);color:var(--text)}:root[data-theme="light"] .nav-item[aria-current="page"] .nav-mark{color:var(--green)}:root[data-theme="light"] .bar-track,:root[data-theme="light"] .mini-bar,:root[data-theme="light"] .donut:before{background:var(--surface-3)}:root[data-theme="light"] .list-row{border-color:var(--line)}:root[data-theme="light"] .alert-symbol{background:var(--surface-3);color:var(--blue)}:root[data-theme="light"] .alert-row.warning .alert-symbol{background:#fff2e1;color:#7b4200}:root[data-theme="light"] .badge.good{color:#006b36}:root[data-theme="light"] .badge.bad{color:#b00020}:root[data-theme="light"] .badge.warn{color:#784900}:root[data-theme="light"] .badge.running{color:#0054a6}
:root[data-theme="light"]{color-scheme:light;--bg:rgb(242, 242, 247);--sidebar:rgb(229, 229, 234);--surface:rgb(255, 255, 255);--card:rgb(248, 248, 250);--surface-2:rgb(248, 248, 250);--surface-3:rgb(209, 209, 214);--line:rgb(199, 199, 204);--gray-2:rgb(174, 174, 178);--gray-mid:rgb(142, 142, 147);--text:rgb(28, 28, 30);--sub:rgb(72, 72, 74);--muted:rgb(72, 72, 74);--blue:#1769aa;--cyan:rgb(0, 200, 83);--green:rgb(0, 200, 83);--green-glow:rgb(48, 209, 88);--red:rgb(255, 56, 60);--red-strong:rgb(233, 21, 45);--glass:rgba(255, 255, 255, 0.65);--glass-border:rgba(255, 255, 255, 0.80);--highlight:rgba(255, 255, 255, 0.30);--shadow:rgba(0, 0, 0, 0.12);--green-glow-shadow:rgba(48, 209, 88, 0.30);--red-glow-shadow:rgba(233, 21, 45, 0.30);--purple:#6b4dc3;--orange:#995000;--focus:#005fcc}
*{box-sizing:border-box}html{background:var(--bg);scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;font-variant-numeric:tabular-nums}button,input{font:inherit}button{color:inherit}
.theme-toolbar{display:flex;align-items:center;justify-content:flex-end;gap:8px;margin:0;color:var(--sub);font-size:12px}.theme-toolbar select{min-width:104px;min-height:44px;padding:6px 8px;border:1px solid var(--line);border-radius:8px;background:var(--surface);color:var(--text)}.theme-toolbar select:focus-visible{outline:2px solid var(--focus);outline-offset:2px}
.skip-link{position:fixed;z-index:100;top:8px;left:8px;display:flex;min-height:44px;align-items:center;transform:translateY(-150%);background:#fff;color:#111;padding:10px 14px;border-radius:6px}.skip-link:focus{transform:none}:focus-visible{outline:2px solid var(--focus);outline-offset:2px}
.app-shell{min-height:100vh;display:grid;grid-template-columns:208px minmax(0,1fr)}.sidebar{position:sticky;top:0;height:100vh;display:flex;flex-direction:column;padding:18px 10px 14px;background:var(--sidebar);border-right:1px solid var(--line);min-width:0}
.brand{height:52px;display:flex;align-items:center;gap:12px;padding:0 12px 15px;margin-bottom:12px;border-bottom:1px solid var(--line);font-size:18px;font-weight:750;letter-spacing:.16em}.brand-symbol{width:28px;height:26px;position:relative;display:inline-block;flex:none}.brand-symbol:before,.brand-symbol:after{content:"";position:absolute;bottom:0;border-style:solid}.brand-symbol:before{left:0;border-width:0 13px 24px;border-color:transparent transparent #6ebaff}.brand-symbol:after{right:0;border-width:0 8px 15px;border-color:transparent transparent #a9cfff}
.sidebar nav{display:grid;gap:4px;overflow:auto}.nav-item{width:100%;min-height:40px;display:flex;align-items:center;gap:11px;padding:7px 10px;border:0;border-radius:7px;background:transparent;color:var(--sub);text-align:left;cursor:pointer}.nav-item:hover{background:var(--surface-3);color:var(--text)}.nav-item[aria-current="page"]{background:#1c2a40;color:#fff;box-shadow:inset 3px 0 var(--blue)}.nav-mark{width:18px;height:18px;display:grid;place-items:center;flex:none;font-size:15px}.nav-item[aria-current="page"] .nav-mark{color:var(--blue)}
.workspace{margin-top:auto;padding:12px;border:1px solid var(--line);border-radius:9px;background:var(--surface)}.workspace small,.workspace span{display:block;color:var(--muted)}.workspace strong{display:block;margin:3px 0 9px;font-size:15px}.workspace-state{display:flex!important;align-items:center;gap:7px;color:var(--sub)!important}.state-dot{width:8px;height:8px;border-radius:50%;background:var(--green);flex:none}
.main{min-width:0;padding:18px 20px 22px}.topbar{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:14px}.welcome{color:var(--muted);font-size:12px}.topbar h1{margin:1px 0;font-size:clamp(21px,2vw,29px);line-height:1.12;letter-spacing:.035em}.subtitle{margin:2px 0 0;color:var(--sub);font-size:13px}.top-actions{display:flex;align-items:center;gap:9px}.search{width:min(250px,25vw);height:36px;padding:0 11px;border:1px solid var(--line);border-radius:8px;background:#0d1421;color:var(--text)}.action{min-height:36px;padding:7px 11px;border:1px solid var(--line);border-radius:8px;background:var(--surface);cursor:pointer}.action:hover{background:var(--surface-3)}
.live-row{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.status-list{display:flex;gap:8px;flex-wrap:wrap}.status{display:flex;align-items:center;gap:8px;min-height:32px;padding:5px 10px;border:1px solid var(--line);border-radius:8px;background:var(--surface);color:var(--sub);font-size:12px}.status b{color:var(--text);font-weight:550}.status .state-dot{width:7px;height:7px}.status.offline .state-dot{background:var(--red)}.live-note{white-space:nowrap;color:var(--sub);font-size:12px}
.grid{display:grid;gap:10px;min-width:0}.kpis{grid-template-columns:repeat(6,minmax(0,1fr));margin-bottom:10px}.card,.panel{min-width:0;border:1px solid var(--line);border-radius:9px;background:linear-gradient(145deg,#121c2c,#101725)}.kpi{position:relative;min-height:100px;padding:13px 14px 11px;overflow:hidden}.kpi-head{display:flex;align-items:center;gap:8px}.kpi-icon{width:30px;height:30px;display:grid;place-items:center;border-radius:9px;background:#18324a;color:var(--cyan);font-size:15px;font-weight:700}.kpi-icon.purple{background:#2c2145;color:#b597ff}.kpi-icon.green{background:#16382f;color:#4be2ac}.kpi-icon.orange{background:#3a2b1d;color:#ffb34f}.kpi-label{color:var(--sub);font-size:11px;line-height:1.2}.kpi-value{margin-top:2px;font-size:21px;font-weight:700;line-height:1.1;letter-spacing:.01em}.kpi-foot{margin-top:5px;color:var(--muted);font-size:10px;line-height:1.2}.panel{padding:12px 13px}.panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:8px;margin-bottom:6px}.panel h2{margin:0;font-size:14px;font-weight:650}.panel-sub{margin:2px 0 0;color:var(--muted);font-size:11px}.panel-link{min-height:32px;display:inline-flex;align-items:center;gap:4px;color:var(--blue);font-size:11px;text-decoration:none;white-space:nowrap}.panel-link:hover{text-decoration:underline}.panel-link:focus-visible{outline:2px solid var(--focus);outline-offset:2px;border-radius:3px}
.chart-grid{grid-template-columns:repeat(4,minmax(0,1fr));margin:10px 0}.chart{min-height:176px}.bars{display:grid;gap:8px}.bar-row{display:grid;grid-template-columns:minmax(66px,1fr) minmax(60px,2fr) auto;align-items:center;gap:8px;font-size:11px}.bar-label{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--sub)}.bar-track{height:9px;overflow:hidden;border-radius:5px;background:#26364b}.bar-fill{height:100%;min-width:0;border-radius:5px;background:var(--cyan)}.bar-value{color:var(--text);text-align:right;white-space:nowrap}.volume-bars{height:112px;display:flex;align-items:end;justify-content:space-around;gap:14px;padding:10px 4px 0;border-bottom:1px solid var(--line)}.volume-item{height:100%;flex:1;display:flex;flex-direction:column;align-items:center;justify-content:end;gap:5px;min-width:0}.volume-bar{width:min(34px,65%);min-height:2px;border-radius:4px 4px 0 0;background:var(--blue)}.volume-label{color:var(--muted);font-size:10px;text-align:center}.volume-value{font-size:10px;color:var(--sub)}
.donut-wrap{display:flex;align-items:center;gap:13px;min-height:115px}.donut{width:105px;height:105px;display:grid;place-items:center;flex:none;border-radius:50%;position:relative}.donut:before{content:"";position:absolute;inset:14px;border-radius:50%;background:var(--surface)}.donut-center{position:relative;text-align:center;font-size:11px;color:var(--sub)}.legend{display:grid;gap:7px;min-width:0;flex:1}.legend-item{display:flex;align-items:center;gap:7px;color:var(--sub);font-size:11px}.legend-swatch{width:8px;height:8px;border-radius:2px;flex:none}.legend-item strong{margin-left:auto;color:var(--text);font-weight:550}.chart-note{margin-top:9px;color:var(--muted);font-size:10px}
.middle-grid{grid-template-columns:minmax(0,1.7fr) minmax(260px,1fr);margin-bottom:10px}.resource-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.resource-card{padding:10px;border:1px solid var(--line);border-radius:7px;background:var(--surface-2)}.resource-card strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px}.resource-card .large{margin-top:4px;font-size:18px;font-weight:650}.resource-card small{color:var(--muted)}.mini-bar{height:6px;margin-top:9px;border-radius:5px;background:#27354a;overflow:hidden}.mini-bar i{display:block;height:100%;border-radius:5px;background:var(--blue)}.list{display:grid}.list-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:center;padding:8px 2px;border-bottom:1px solid #202e40;font-size:11px}.list-row:last-child{border-bottom:0}.list-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--sub)}.list-value{color:var(--text);white-space:nowrap}
.lower-grid{grid-template-columns:minmax(0,1.75fr) minmax(270px,1fr);margin-bottom:10px}.table-wrap{max-width:100%;overflow:auto}table{width:100%;border-collapse:collapse;font-size:11px}th,td{padding:8px 9px;border-bottom:1px solid #202e40;text-align:left;white-space:nowrap}th{color:var(--muted);font-weight:550}td{color:var(--sub)}.task-id{color:var(--text)}.badge{display:inline-flex;align-items:center;padding:2px 7px;border-radius:10px;border:1px solid currentColor;font-size:10px}.badge.good{color:var(--green);background:#12372e}.badge.running{color:var(--blue);background:#142e49}.badge.warn{color:var(--orange);background:#382b1b}.badge.bad{color:var(--red);background:#3a2029}.alerts{display:grid}.alert-row{display:grid;grid-template-columns:24px minmax(0,1fr) auto;gap:8px;align-items:start;padding:9px 0;border-bottom:1px solid #202e40}.alert-row:last-child{border-bottom:0}.alert-symbol{width:22px;height:22px;display:grid;place-items:center;border-radius:50%;background:#213147;color:var(--blue);font-size:12px}.alert-row.warning .alert-symbol{background:#3b2e1b;color:var(--orange)}.alert-message{font-size:11px;color:var(--text)}.alert-time{color:var(--muted);font-size:10px;white-space:nowrap}
.empty{padding:16px 8px;color:var(--sub);font-size:12px}.empty strong{display:block;color:var(--text);margin-bottom:3px}.measurement{color:var(--muted);font-size:10px}.detail[hidden],.overview[hidden]{display:none}.detail{margin-top:10px}.detail-panel{min-height:220px}.view-json{margin:10px 0 0;max-height:65vh;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;word-break:break-word;color:var(--sub);font:12px/1.55 ui-monospace,Consolas,monospace}.graph-columns{display:grid;gap:16px;grid-template-columns:repeat(2,minmax(0,1fr));margin-top:14px}.graph-columns h3{font-size:13px;margin-bottom:8px}.report-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin:12px 0;padding:10px;border:1px solid var(--line);border-radius:8px;background:var(--surface-2)}.report-summary div{display:grid;gap:3px}.report-summary small,.report-field dt{color:var(--muted);font-size:11px}.report-summary strong{font-size:12px;overflow-wrap:anywhere}.report-heading{margin:16px 0 8px;font-size:14px}.report-fields{display:grid;gap:7px;margin:0}.report-field{display:grid;grid-template-columns:minmax(150px,.7fr) minmax(0,2fr);gap:10px;padding:9px 10px;border:1px solid var(--line);border-radius:7px;background:var(--surface-2)}.report-field dt{margin:0}.report-field dd{margin:0;overflow-wrap:anywhere;color:var(--text)}.report-list{display:grid;gap:8px}.report-item{padding:9px;border:1px solid var(--line);border-radius:7px;background:var(--surface)}.report-item h4{margin:0 0 7px;font-size:12px}.report-unavailable{color:var(--muted);font-style:italic}.footer-note{margin-top:10px;text-align:right;color:var(--muted);font-size:10px}
:root .card{background:var(--card);box-shadow:0 6px 16px var(--shadow)}:root .panel{background:var(--surface);box-shadow:0 6px 16px var(--shadow)}:root .search{background:var(--surface-2)}:root .nav-item[aria-current="page"]{background:var(--surface-3);color:var(--text)}:root .mini-bar,:root .bar-track,:root .donut:before{background:var(--surface-3)}:root .list-row,:root th,:root td,:root .alert-row{border-color:var(--line)}
:root[data-theme="light"] body{background:var(--bg)}:root[data-theme="light"] .workspace,:root[data-theme="light"] .action,:root[data-theme="light"] .report-item{background:var(--surface);color:var(--text)}:root[data-theme="light"] .sidebar{background:var(--sidebar)}:root[data-theme="light"] .report-summary,:root[data-theme="light"] .report-field,:root[data-theme="light"] .resource-card{background:var(--surface-2)}:root[data-theme="light"] .kpi-icon,:root[data-theme="light"] .kpi-icon.purple,:root[data-theme="light"] .kpi-icon.green,:root[data-theme="light"] .kpi-icon.orange{background:var(--surface-3);color:var(--text)}:root[data-theme="light"] .badge.good,:root[data-theme="light"] .badge.running,:root[data-theme="light"] .badge.warn,:root[data-theme="light"] .badge.bad{background:var(--surface-2)}:root[data-theme="light"] .search,:root[data-theme="light"] .action,:root[data-theme="light"] select{border-color:var(--line)}
#kpis>.empty{grid-column:1/-1}.workspace-state:not(.online):not(.offline) .state-dot{background:var(--blue)}.workspace-state.online .state-dot{background:var(--green)}.workspace-state.offline .state-dot{background:var(--red)}
@media(max-width:1260px){.app-shell{grid-template-columns:190px minmax(0,1fr)}.main{padding:15px}.kpis{grid-template-columns:repeat(3,minmax(0,1fr))}.chart-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.resource-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:820px){.app-shell{grid-template-columns:1fr}.sidebar{position:relative;height:auto;padding:9px 12px;border-right:0;border-bottom:1px solid var(--line)}.brand{height:39px;margin:0 0 8px;padding:0 5px 8px}.sidebar nav{display:flex;width:100%;min-width:0;max-width:100%;overflow-x:auto;padding-bottom:3px}.nav-item{width:auto;flex:none;min-height:38px;padding:6px 9px}.nav-mark{display:none}.workspace{display:none}.topbar{align-items:flex-start}.middle-grid,.lower-grid{grid-template-columns:minmax(0,1fr)}}
@media(max-width:560px){.main{padding:12px}.topbar{display:grid;gap:10px;min-width:0}.top-actions{display:grid;grid-template-columns:minmax(0,1fr) auto auto;width:100%;min-width:0;gap:6px}.search{width:100%;min-width:0}.kpis{grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.kpi{min-height:91px;padding:10px}.kpi-value{font-size:20px}.chart-grid{grid-template-columns:1fr}.chart{min-height:160px}.status-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));width:100%}.status{font-size:10px;padding:4px 7px}.live-row{align-items:flex-start;flex-direction:column}.live-note{white-space:normal}.resource-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.graph-columns{grid-template-columns:1fr}.table-wrap{overflow-x:auto}th,td{padding:8px 7px}.panel{padding:11px}}
@media(max-width:360px){.kpis,.resource-grid{grid-template-columns:1fr}.nav-item{font-size:12px}.topbar h1{font-size:20px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,*::before,*::after{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}
.visually-hidden{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}.workspace-state.offline .state-dot{background:var(--red)}.main{padding:13px 15px}.topbar{margin-bottom:10px}.live-row{margin-bottom:9px}.grid{gap:8px}.kpi{min-height:86px;padding:10px 12px}.kpi-value{font-size:21px}.panel{padding:10px 11px}.chart{min-height:145px}.volume-bars{height:94px}.middle-grid,.lower-grid{margin-bottom:8px}.resource-card{padding:8px}.alert-row{padding:6px 0}.footer-note{margin-top:6px}
@media(max-width:820px){.nav-item{min-height:44px}}
@media(max-width:560px){body{font-size:16px}.search,.action{height:44px;min-height:44px}}
@media(max-width:560px){.report-field{grid-template-columns:minmax(0,1fr)}}
</style></head><body><a class="skip-link" href="#main-content">Pular para o conteúdo</a><div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-symbol" aria-hidden="true"></span><span>LUMENVA</span></div><nav id="sidebar-nav" aria-label="Navegação principal">${navigation}</nav><section class="workspace" aria-label="Workspace atual"><small>Workspace</small><strong id="workspace-name">Lumenva</strong><span class="workspace-state"><i class="state-dot" aria-hidden="true"></i><span id="workspace-status">Gateway verificando</span></span></section></aside><main class="main" id="main-content" tabindex="-1"><header class="topbar"><div><div class="welcome">Bem-vindo de volta</div><h1>LUMENVA CONTEXT GATEWAY</h1><p class="subtitle">Observabilidade, economia de contexto e validação operacional</p></div><div class="top-actions"><label class="visually-hidden" for="task-search">Buscar nas tarefas</label><input class="search" id="task-search" type="search" placeholder="Buscar nas tarefas…" autocomplete="off"><button class="action" id="refresh" type="button">Atualizar</button></div></header>
<div class="theme-toolbar"><label for="theme-select">Tema</label><select id="theme-select"><option value="system">Sistema</option><option value="light">Claro</option><option value="dark">Escuro</option></select></div>
<div class="live-row"><div class="status-list" id="health" role="group" aria-label="Estado dos serviços" aria-live="polite"></div><div class="live-note" id="live" role="status" aria-live="polite">Conectando…</div></div>
<div id="overview-content" class="overview"><section class="grid kpis" id="kpis" aria-label="Indicadores principais"></section>
<section class="grid chart-grid" aria-label="Gráficos de observabilidade"><article class="panel chart"><div class="panel-head"><div><h2>Volume de contexto</h2><p class="panel-sub">Original, entregue e economia</p></div><span class="measurement" id="volume-source"></span></div><div id="volume"></div></article><article class="panel chart"><div class="panel-head"><div><h2>Distribuição da economia</h2><p class="panel-sub">Por executor observado</p></div></div><div id="distribution"></div></article><article class="panel chart"><div class="panel-head"><div><h2>Economia por executor</h2><p class="panel-sub">Tokens estimados evitados</p></div></div><div id="executors"></div></article><article class="panel chart"><div class="panel-head"><div><h2>Consumo por ferramenta</h2><p class="panel-sub">Tokens registrados</p></div></div><div id="tools"></div></article></section>
<section class="grid middle-grid"><article class="panel"><div class="panel-head"><div><h2>Executores</h2><p class="panel-sub">Atividade e economia observadas</p></div></div><div id="agents" class="resource-grid"></div></article><article class="panel"><div class="panel-head"><div><h2>Plugins mais usados</h2><p class="panel-sub">Consumo observado</p></div></div><div id="plugins" class="list"></div></article></section>
<section class="grid lower-grid"><article class="panel"><div class="panel-head"><div><h2>Tarefas recentes</h2><span id="task-count" class="panel-sub"></span><span id="task-filter-status" class="panel-sub" aria-live="polite"></span></div><a class="panel-link" data-view-link="Tasks" href="?view=Tasks">Ver todas<span aria-hidden="true"> →</span></a></div><div class="table-wrap" id="tasks" role="region" aria-label="Prévia das tarefas recentes" tabindex="0"></div></article><article class="panel"><div class="panel-head"><div><h2>Alertas e eventos</h2><span id="alert-count" class="badge warn">0</span></div><a class="panel-link" data-view-link="Alerts" href="?view=Alerts">Ver todos<span aria-hidden="true"> →</span></a></div><div id="alerts" class="alerts"></div></article></section>
<section class="panel"><div class="panel-head"><div><h2>Validação MCG</h2><p class="panel-sub">Qualidade, cobertura e evidências</p></div><span id="trust-status" class="badge">Não validado</span></div><div class="resource-grid" id="trust"></div></section><div class="footer-note" id="updated-at"></div></div>
<section id="detail-content" class="detail" hidden aria-labelledby="detail-title"><article class="panel detail-panel"><div class="panel-head"><div><h2 id="detail-title" tabindex="-1">Detalhes</h2><p id="detail-source" class="panel-sub"></p></div><span id="detail-measurement" class="measurement"></span></div><p id="view-status" class="visually-hidden" role="status" aria-live="polite"></p><div id="view-panel" tabindex="-1" role="region" aria-labelledby="detail-title" aria-busy="false"></div></article></section></main></div>
<script>
const $=id=>document.getElementById(id),num=v=>Number.isFinite(v)?Intl.NumberFormat('pt-BR').format(v):'—',pct=v=>Number.isFinite(v)?Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}).format(v)+'%':'—',esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),statusLabel={DONE:'Concluída',RUNNING:'Em execução',DISPATCHED:'Enviada',BLOCKED:'Bloqueada',FAILED:'Falhou',CANCELLED:'Cancelada',INCOMPLETE:'Incompleta',WORKING:'Trabalhando',TESTING:'Testando',BUILDING:'Compilando',CI_RUNNING:'CI em execução',RETRYING:'Tentando novamente'},trustLabel={UNVALIDATED:'Não validado',VALIDATED:'Validado',PASS:'Validado',FAIL:'Falha na validação',DEGRADED:'Degradado'},colors=['var(--cyan)','var(--purple)','var(--orange)','var(--blue)'];
let statsData=null, viewData={}, pollTimer=null, currentView='Overview', viewLoadId=0;
function badge(type){const labels={exact:'Exato',estimated:'Estimado',unavailable:'Indisponível'};return '<span class="measurement">'+(labels[type]||labels.unavailable)+'</span>'}
function empty(title,detail){return '<div class="empty"><strong>'+esc(title)+'</strong>'+esc(detail)+'</div>'}
function kpi(label,value,detail,color,measure){return '<article class="card kpi"><div class="kpi-head"><span class="kpi-icon '+color+'" aria-hidden="true">'+({blue:'◫',purple:'↓',green:'↘',orange:'%' }[color]||'•')+'</span><div><div class="kpi-label">'+label+'</div><div class="kpi-value">'+value+'</div></div></div><div class="kpi-foot">'+detail+(measure?' · '+badge(measure):'')+'</div></article>'}
function renderVolume(d){const vals=[['Original',d.original_chars,'var(--blue)'],['Entregue',d.delivered_chars,'var(--cyan)'],['Evitado',d.saved_chars,'var(--green)']],max=Math.max(0,...vals.map(x=>Number.isFinite(x[1])?x[1]:0));if(!max){$('volume').innerHTML=empty('Sem amostras de contexto','A visualização aparece após a primeira compilação observada.');return}$('volume').innerHTML='<div class="volume-bars" role="img" aria-label="Volume de contexto: '+vals.map(x=>x[0]+' '+num(x[1])).join(', ')+'">'+vals.map(x=>'<div class="volume-item"><span class="volume-value">'+num(x[1])+'</span><div class="volume-bar" style="height:'+Math.max(x[1]===null?0:2,(x[1]||0)/max*82)+'%;background:'+x[2]+'"></div><span class="volume-label">'+x[0]+'</span></div>').join('')+'</div><div class="chart-note">Valores de contexto em caracteres; economia calculada sobre compilações registradas.</div>';}
function renderDistribution(rows){const usable=rows.filter(x=>x.estimated_tokens_saved>0).slice(0,4),total=usable.reduce((a,x)=>a+x.estimated_tokens_saved,0);if(!total){$('distribution').innerHTML=empty('Sem distribuição observada','Não há economia atribuível a executores ainda.');return}let at=0;const segments=usable.map((x,i)=>{const start=at;at+=x.estimated_tokens_saved/total*100;return colors[i%colors.length]+' '+start+'% '+at+'%'}).join(', ');$('distribution').innerHTML='<div class="donut-wrap"><div class="donut" style="background:conic-gradient('+segments+')" role="img" aria-label="Distribuição da economia entre executores"><div class="donut-center">'+num(total)+'<br>tokens est.</div></div><div class="legend">'+usable.map((x,i)=>'<div class="legend-item"><i class="legend-swatch" style="background:'+colors[i%colors.length]+'" aria-hidden="true"></i><span>'+esc(x.executor)+'</span><strong>'+pct(x.estimated_tokens_saved/total*100)+'</strong></div>').join('')+'</div></div><div class="chart-note">Estimativas baseadas em bytes de evidência.</div>'}
function renderBars(target,rows,label,value,color){if(!rows.length){$(target).innerHTML=empty('Sem dados observados','Este painel será preenchido quando houver telemetria.');return}const max=Math.max(1,...rows.map(x=>Number.isFinite(x[value])?x[value]:0));$(target).innerHTML='<div class="bars">'+rows.slice(0,5).map((x,i)=>'<div class="bar-row"><span class="bar-label" title="'+esc(x[label])+'">'+esc(x[label])+'</span><span class="bar-track"><i class="bar-fill" style="display:block;width:'+((x[value]||0)/max*100)+'%;background:'+colors[i%colors.length]+'"></i></span><span class="bar-value">'+num(x[value])+'</span></div>').join('')+'</div>'}
function renderTasks(rows){
  const query=$('task-search').value.trim().toLocaleLowerCase('pt-BR');
  const filtered=rows.filter(t=>!query||[t.task_id,t.executor,t.agent,t.runtime,t.plugin,statusLabel[t.status]||t.status].join(' ').toLocaleLowerCase('pt-BR').includes(query));
  $('task-count').textContent=filtered.length+' de '+rows.length;$('task-filter-status').textContent=query?'Filtro ativo':'';
  if(!filtered.length){$('tasks').innerHTML=query?empty('Nenhuma tarefa encontrada','Ajuste a busca para ver outras tarefas.'):empty('Nenhuma tarefa registrada','As execuções aparecerão aqui quando o Gateway observar tasks.');return}
  const data=filtered.slice(0,query?20:1);
  $('tasks').innerHTML='<table><caption class="visually-hidden">Tarefas recentes</caption><thead><tr><th scope="col">ID</th><th scope="col">Tarefa / Estado</th><th scope="col">Executor</th><th scope="col">Status</th><th scope="col">Bytes fonte → resultado</th><th scope="col">Economia estimada</th><th scope="col">Início</th></tr></thead><tbody>'+data.map(t=>'<tr><td class="task-id">'+esc(t.task_id)+'</td><td>'+esc(statusLabel[t.detail_status]||t.detail_status||t.task_id)+'</td><td>'+esc(t.executor)+'</td><td><span class="badge '+({DONE:'good',RUNNING:'running',BLOCKED:'warn',FAILED:'bad'}[t.status]||'')+'">'+esc(statusLabel[t.status]||t.status)+'</span></td><td>'+num(t.original_chars)+' → '+num(t.delivered_chars)+'</td><td>'+num(t.tokens_saved)+' tok. est. · '+pct(t.reduction_percent)+'</td><td>'+esc(t.created_at?new Date(t.created_at).toLocaleString('pt-BR'):'—')+'</td></tr>').join('')+'</tbody></table>';
}
function renderAlerts(items){$('alert-count').textContent=String(items.length);$('alerts').innerHTML=items.length?items.slice(0,3).map(a=>'<div class="alert-row '+(['warning','warn','high'].includes(String(a.severity||a.level).toLowerCase())?'warning':'')+'"><span class="alert-symbol" aria-hidden="true">'+(['warning','warn','high','critical'].includes(String(a.severity||a.level).toLowerCase())?'!':'i')+'</span><span class="alert-message">'+esc(a.message||a.type||a.alert_id||'Evento registrado')+'</span><time class="alert-time">'+esc(a.timestamp?new Date(a.timestamp).toLocaleString('pt-BR'):'')+'</time></div>').join(''):empty('Nenhum alerta ativo','Novos alertas observados serão exibidos aqui.')}
function renderStats(d,health){
  statsData=d;
  $('overview-content').setAttribute('aria-busy','false');
  $('kpis').innerHTML=[kpi('Tarefas concluídas',num(d.tasks_processed),'Total','blue','exact'),kpi('Tarefas ativas',num(d.tasks_active),'Em execução','blue','exact'),kpi('Tokens originais',num(d.estimated_tokens_original),'Original','purple',d.measurement_type),kpi('Tokens entregues',num(d.estimated_tokens_delivered),'Entregue','blue',d.measurement_type),kpi('Tokens economizados',num(d.estimated_tokens_saved),'Evitado','green',d.measurement_type),kpi('Redução',pct(d.reduction_percent),'Compilações','orange',d.measurement_type)].join('');
  const labels=[['Daemon',health.daemon],['Wire',health.wire],['Workspace',health.workspace_online?'ONLINE':'OFFLINE'],['SSE',document.getElementById('live').dataset.mode==='live'?'ONLINE':'POLLING']];
  $('health').innerHTML=labels.map(([name,value])=>'<div class="status '+(String(value).includes('OFFLINE')?'offline':'')+'"><i class="state-dot" aria-hidden="true"></i><b>'+name+'</b> '+esc(value)+'</div>').join('');
  $('workspace-name').textContent=health.workspace||'Lumenva';$('workspace-status').textContent=health.workspace_online?'Gateway ativo':'Gateway local';$('workspace-status').parentElement.classList.toggle('online',Boolean(health.workspace_online));$('workspace-status').parentElement.classList.toggle('offline',!health.workspace_online);
  renderVolume(d);const executors=Object.values(d.by_executor||{}).filter(x=>x.estimated_tokens_saved>0).sort((a,b)=>b.estimated_tokens_saved-a.estimated_tokens_saved);renderDistribution(executors);renderBars('executors',executors,'executor','estimated_tokens_saved');renderBars('tools',d.by_tool||[],'tool','tokens');
  const agents=Object.values(d.by_executor||{}).filter(x=>x.tasks_processed||x.tasks_active);$('agents').innerHTML=agents.length?agents.slice(0,4).map(x=>'<div class="resource-card"><strong>'+esc(x.executor)+'</strong><div><span class="large">'+num(x.estimated_tokens_saved)+'</span><small>tokens estimados · '+num(x.tasks_active)+' ativos</small></div></div>').join(''):empty('Sem atividade de executor observada','Executores aparecem após registros de contexto ou tasks.');
  renderBars('plugins',d.by_plugin||[],'plugin','tokens');renderTasks(d.tasks||[]);renderAlerts([...(d.alerts||[]),...(d.ceo_inbox||[])]);
  const trust=d.trust||{};$('trust-status').textContent=trustLabel[trust.status]||trust.status||'Indisponível';$('trust').innerHTML=[['Score',Number.isFinite(trust.score)?num(trust.score)+'/100':'—'],['Recall de contexto',pct(trust.context_recall)],['Evidence grounding',pct(trust.evidence_grounding)],['Economia preservando qualidade',pct(trust.quality_preserving_saving)]].map(([a,b])=>'<div class="resource-card"><small>'+a+'</small><div class="large">'+b+'</div></div>').join('');
  $('volume-source').textContent=d.measurement_type==='estimated'?'Estimado':'Fonte indisponível';$('updated-at').textContent='Atualizado '+new Date().toLocaleTimeString('pt-BR');
}
async function selectView(name,persist=true){currentView=name;const requestId=++viewLoadId;if(persist)history.pushState({view:name},'',name==='Overview'?location.pathname:location.pathname+'?view='+encodeURIComponent(name));document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-current',String(b.dataset.view===name?'page':'false')));const overview=name==='Overview';$('overview-content').hidden=!overview;$('detail-content').hidden=overview;if(overview)return;const labels=${JSON.stringify(Object.fromEntries(views))},label=labels[name]||name;$('detail-title').textContent=label;$('detail-title').focus({preventScroll:true});$('view-status').textContent='Carregando relatório: '+label+'.';$('view-panel').setAttribute('aria-busy','true');$('view-panel').innerHTML=empty('Carregando dados…','Buscando observações desta área.');window.scrollTo(0,0);try{const response=await fetch('/api/views',{cache:'no-store'});if(!response.ok)throw new Error('view registry unavailable');viewData=(await response.json()).views||{};}catch{if(requestId!==viewLoadId)return;$('view-panel').innerHTML=empty('Não foi possível carregar esta área','Selecione esta área novamente para tentar outra vez.');$('view-status').textContent='Falha ao carregar o relatório: '+label+'. Selecione esta área novamente para tentar outra vez.';$('view-panel').setAttribute('aria-busy','false');return}if(requestId!==viewLoadId)return;renderView(name);$('view-status').textContent=viewData[name]?'Relatório carregado: '+label+'.':'Relatório indisponível: '+label+'. A API não retornou dados.';$('view-panel').setAttribute('aria-busy','false')}
const reportLabels={status:'Estado',count:'Quantidade',records:'Registros',samples:'Amostras',registered_count:'Itens registrados',measurement_type:'Qualidade da medição',timestamp:'Atualizado em',source:'Fonte dos dados',scope:'Escopo dos dados',limitations:'Limitações dos dados',tasks:'Tarefas',traces:'Traces',agents:'Agentes',tools:'Ferramentas',plugins:'Plugins',mcps:'MCPs',items:'Itens',executions:'Execuções',usage:'Uso observado',input_tokens:'Tokens de entrada',cached_tokens:'Tokens em cache',output_tokens:'Tokens de saída',reasoning_tokens:'Tokens de raciocínio',total_tokens:'Tokens totais',duration_ms:'Duração (ms)',cost_usd:'Custo (USD)',cache_hits:'Acertos de cache',cache_misses:'Falhas de cache',cache_hit_rate:'Taxa de acerto',tokens_avoided_estimated:'Tokens evitados (estimativa)',context_reused:'Contexto reutilizado',types:'Tipos de histórico',nodes:'Entidades',edges:'Relações',namespace:'Namespace',query:'Consulta',readOnly:'Somente leitura',latest:'Registro mais recente',retrievals:'Recuperações',events:'Eventos',paired_runs:'Avaliações pareadas',score:'Pontuação',baseline:'Linha de base',mcg:'MCG',regressions:'Regressões',alerts:'Alertas',severity:'Severidade',message:'Mensagem',created_at:'Criado em',updated_at:'Atualizado em',task_id:'ID da tarefa',executor:'Executor',agent:'Agente',runtime:'Runtime',plugin:'Plugin',reduction_percent:'Redução',measurement_basis:'Base da medição',health:'Saúde',success_rate:'Taxa de sucesso',latency_ms:'Latência (ms)',confidence:'Confiança',error:'Erro',warning:'Aviso',warnings:'Avisos',metrics:'Métricas'};
const reportScopeLabels={period:'Período',record_limit:'Limite de registros',limit_reached:'Limite atingido',last_observed_at:'Última observação dos dados',sample_coverage:'Cobertura da amostra',observed_pairs:'Pares observados',required_pairs:'Pares necessários',coverage_percent:'Cobertura do mínimo',minimum_met:'Mínimo atingido',coverage_scope:'Escopo da cobertura',result_coverage:'Cobertura de resultados',tasks_with_result:'Tarefas com resultado',total_tasks:'Total de tarefas',coverage_basis:'Base da cobertura'};
function reportLabel(key){return reportLabels[key]||reportScopeLabels[key]||key.replace(/_/g,' ').replace(/\b\w/g,char=>char.toUpperCase())}
function renderReportValue(value){if(value===null||value===undefined)return '<span class="report-unavailable">Indisponível — sem observação</span>';if(Array.isArray(value)){if(!value.length)return '<span class="report-unavailable">Nenhum registro observado</span>';return '<div class="report-list">'+value.map((item,index)=>'<article class="report-item"><h4>'+esc(item&&typeof item==='object'?(item.name||item.task_id||item.id||item.type||'Registro '+(index+1)):'Registro '+(index+1))+'</h4>'+renderReportFields(item&&typeof item==='object'?item:{valor:item})+'</article>').join('')+'</div>'}if(value&&typeof value==='object')return renderReportFields(value);if(typeof value==='boolean')return value?'Sim':'Não';return esc(value)}
function renderReportFields(value){return '<dl class="report-fields">'+Object.entries(value).map(([key,item])=>'<div class="report-field"><dt>'+esc(reportLabel(key))+'</dt><dd>'+renderReportValue(item)+'</dd></div>').join('')+'</dl>'}
function renderView(name){const v=viewData[name];$('detail-source').textContent=v?.source||'Fonte não informada';$('detail-measurement').textContent=({exact:'Exato',estimated:'Estimado',unavailable:'Indisponível'}[v?.measurement_type]||'Indisponível');if(!v){$('view-panel').innerHTML=empty('View indisponível','A API não retornou dados para esta área.');return}const hidden=new Set(['source','timestamp','measurement_type']);const entries=Object.entries(v).filter(([key])=>!hidden.has(key));const state=v.status||'OBSERVED';const stateLabel=({OBSERVED:'Observado',PARTIAL:'Parcial',UNAVAILABLE:'Indisponível',UNVALIDATED:'Ainda não validado',VALIDATED:'Validado',PASS:'Aprovado',FAIL:'Falhou',DEGRADED:'Degradado'}[state]||state);const summary='<section class="report-summary" aria-label="Resumo do relatório"><div><small>Estado</small><strong>'+esc(stateLabel)+'</strong></div><div><small>Qualidade</small><strong>'+esc(({exact:'Exata',estimated:'Estimativa',unavailable:'Sem medição'}[v.measurement_type]||'Sem medição'))+'</strong></div><div><small>Relatório consultado em</small><strong>'+esc(v.timestamp?new Date(v.timestamp).toLocaleString('pt-BR'):'Sem timestamp')+'</strong></div></section>';if(name==='Graph'&&Array.isArray(v.nodes)&&Array.isArray(v.edges)){const graph='<div class="graph-columns"><section><h3>Entidades ('+v.nodes.length+')</h3>'+renderReportValue(v.nodes)+'</section><section><h3>Relações ('+v.edges.length+')</h3>'+renderReportValue(v.edges)+'</section></div>';$('view-panel').innerHTML=summary+graph;return}$('view-panel').innerHTML=summary+'<h3 class="report-heading">Detalhes do relatório</h3>'+ (entries.length?renderReportFields(Object.fromEntries(entries)):empty('Sem detalhes adicionais','A fonte não forneceu outros campos para esta área.'))}
async function load(){try{if(!statsData)$('overview-content').setAttribute('aria-busy','true');const [sr,hr]=await Promise.all(['/api/stats','/api/health'].map(u=>fetch(u,{headers:{accept:'application/json'}})));if(!sr.ok||!hr.ok)throw new Error('API indisponível');const [s,h]=await Promise.all([sr.json(),hr.json()]);renderStats(s,h)}catch(err){$('overview-content').setAttribute('aria-busy','false');$('live').textContent='Falha ao atualizar. Tente novamente.';$('live').dataset.mode='error';$('live').classList.add('offline');if(!statsData){$('overview-content').innerHTML=empty('Dashboard indisponível','Não foi possível ler os dados locais. Use Atualizar para tentar novamente.')}}}
const themeSelect=$('theme-select');
const themePreferenceKey='mcg-dashboard-theme';
function applyTheme(preference){const systemDark=window.matchMedia?.('(prefers-color-scheme: dark)').matches??true;const theme=preference==='system'?(systemDark?'dark':'light'):preference;document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme;const themeColor=document.querySelector('meta[name="theme-color"]');if(themeColor)themeColor.content=theme==='dark'?'rgb(0, 0, 0)':'rgb(242, 242, 247)'}
let themePreference='system';
try{const saved=localStorage.getItem(themePreferenceKey);if(['system','light','dark'].includes(saved))themePreference=saved}catch{}
themeSelect.value=themePreference;applyTheme(themePreference);
themeSelect.addEventListener('change',()=>{themePreference=themeSelect.value;try{localStorage.setItem(themePreferenceKey,themePreference)}catch{}applyTheme(themePreference)});
window.matchMedia?.('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(themePreference==='system')applyTheme('system')});
function initializeLoading(){
  $('overview-content').setAttribute('aria-busy','true');
  $('alerts').setAttribute('aria-live','polite');
  $('kpis').innerHTML=empty('Carregando indicadores…','Lendo métricas observadas do Gateway.');
  $('health').innerHTML='<div class="status"><i class="state-dot" aria-hidden="true"></i><b>Serviços</b> verificando…</div>';
  for(const id of ['volume','distribution','executors','tools','agents','plugins','tasks','alerts','trust'])$(id).innerHTML=empty('Carregando dados…','Aguardando a leitura inicial do Gateway.');
}
initializeLoading();document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>selectView(b.dataset.view)));window.addEventListener('popstate',()=>{const requested=new URLSearchParams(location.search).get('view'),valid=[...document.querySelectorAll('[data-view]')].some(button=>button.dataset.view===requested);selectView(valid?requested:'Overview',false)});const initialView=new URLSearchParams(location.search).get('view');if(initialView&&[...document.querySelectorAll('[data-view]')].some(button=>button.dataset.view===initialView))selectView(initialView,false);$('task-search').addEventListener('input',()=>statsData&&renderTasks(statsData.tasks||[]));$('refresh').addEventListener('click',()=>load());const stream=new EventSource('/api/events');stream.onopen=()=>{if(pollTimer){clearInterval(pollTimer);pollTimer=null}$('live').textContent='AO VIVO · Atualização automática';$('live').dataset.mode='live';$('live').classList.remove('offline')};stream.addEventListener('update',()=>load());stream.onerror=()=>{stream.close();$('live').textContent='Atualização por polling · 2s';$('live').dataset.mode='polling';if(!pollTimer)pollTimer=setInterval(load,2000)};load();
</script></body></html>`;
